name: Build
on:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: ['8', '11', '17']
        os: [ubuntu-latest]
    steps:

    - name: Check out repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        fetch-depth: 0

    # Install Java.
    - name: Set up JDK
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
      with:
        distribution: temurin
        java-version: ${{ matrix.java_version }}
        cache: maven

    - name: Build
      run: |
        ./mvnw clean package
        echo ${{ matrix.java_version }}

    # Build provenance
    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@897ed5eab6ed058a474202017ada7f40bfa52940 # v1.0.0
      with:
        subject-path: target/*.jar
